# -*- coding: utf-8 -*-
"""BankNote.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lFzSCd-o_vzFOaKCaJ9bLeCYft3KJwYV
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

train_data = pd.read_csv("BankNote_Authentication.csv")

train_data.head()

train_data.shape

train_data.isna().sum()

train_data.info()

train_data.isnull().sum()

X = train_data.drop(['class'], axis=1)

y = train_data['class']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

X_train.shape, X_test.shape

X_train.dtypes

from sklearn.tree import DecisionTreeClassifier

clf_gini = DecisionTreeClassifier(criterion='gini', max_depth=3, random_state=0)
clf_gini.fit(X_train, y_train)

y_predict = clf_gini.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_predict)

